FROM couchdb:3.4

LABEL org.opencontainers.image.title="obsidian-livesync-couchdb" \
      org.opencontainers.image.description="CouchDB image preconfigured for Obsidian LiveSync" \
      org.opencontainers.image.source="https://github.com/vrtmrz/obsidian-livesync"

EXPOSE 5984
